M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Tue 12 Dec 2023 19:51:11
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-12T19:51:11+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.9949Y-2.7676
X6.2224Y-2.7676
T0
M30
