M48
; DRILL file {KiCad 8.0.1-8.0.1-1~ubuntu22.04.1} date 2024-06-04T22:30:17+1000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-04T22:30:17+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-8.0.1-1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.9949Y-2.7676
X6.2224Y-2.7676
M30
